controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

scan_barcode:
    path: /scan-barcode
    controller: App\Controller\BarcodeScannerController::scanBarcode
