<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQFOGzdx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQFOGzdx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQFOGzdx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQFOGzdx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerQFOGzdx\App_KernelDevDebugContainer([
    'container.build_hash' => 'QFOGzdx',
    'container.build_id' => 'd1fe8a13',
    'container.build_time' => 1705660461,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQFOGzdx');
