<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerF5JI2pX\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerF5JI2pX/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerF5JI2pX.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerF5JI2pX\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerF5JI2pX\App_KernelDevDebugContainer([
    'container.build_hash' => 'F5JI2pX',
    'container.build_id' => '41ee6835',
    'container.build_time' => 1706118197,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerF5JI2pX');
